services:
  three-render-viewer:
    container_name: three-render-viewer
    image: cainmaila/three-render
    ports:
      - 3000:3000
    volumes:
      - your-config-in-model:/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]